### ISSUE TITLE
another issue with importing

### ISSUE THREAD

**Issue by devsnek** [tomasbasham/dominos#2]
with your current setup, the way to import dominos is `from dominos.dominos import Dominos`
not the way you say in the readme. This isn't necessarily an "issue" but it makes things less nice to look at.

**Comment by tomasbasham** [comment]
I don't experience the same "issue". I have been able to import the package the way I describe

```
(test)Tomass-MacBook-Pro dominos (master)$ python
Python 2.7.10 (default, Oct 23 2015, 18:05:06) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from dominos import Dominos
>>> api = Dominos()
>>> api.get_nearest_store('CF24 4JB')
<Response [200]>
>>> 
```

**Comment by devsnek** [comment]
strange

**Comment by tomasbasham** [comment]
Ok, I have updated the package due to issues in #1 so now it can be imported using the following

```
>>> from dominos.api import Client
>>> api = Client()
>>> api.get_nearest_store('CF24 4JB')
<Response [200]>
>>>
```

Let me know if this works for you

**Comment by devsnek** [comment]
works.
