### ISSUE TITLE
Cannot get Store Context

### ISSUE THREAD

**Issue by jacob-padley** [tomasbasham/dominos#4]
When trying to retrieve the store context, I am given this error:
`dominos.api.ApiError: Cannot fetch store context: 404`
From my understanding, this means that the URL used by the API is incorrect. Any help resolving this would be apprecieated. Also, a documentation explaining the full method for ordering a pizza through this API would be incredibly helpful. Thanks in advance!

**Comment by jacob-padley** [comment]
I have worked out that this is an issue caused by the API endpoints being outdated. I am currently working on a new updated version so we UK people can order fresh pizza the cool way :D

**Comment by NyleCohen** [comment]
Thank you for the help!
